// <auto-generated />
using System;
using MarketService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarketService.Infrastructure.Migrations
{
    [DbContext(typeof(MarketDbContext))]
    [Migration("20251226154623_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarketService.Domain.Entities.Market", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorityPubKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CollateralMint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedTxSignature")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("LastIndexedSlot")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MarketPubKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("MarketSeedId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("ProgramId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at_utc");

                    b.Property<DateTime?>("SettledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("settled_at_utc");

                    b.Property<byte?>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("VaultAuthorityPubKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("VaultPubKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte?>("WinningOutcomeIndex")
                        .HasColumnType("smallint")
                        .HasColumnName("winning_outcome_index");

                    b.HasKey("Id");

                    b.HasIndex("MarketPubKey")
                        .IsUnique();

                    b.HasIndex("AuthorityPubKey", "MarketSeedId")
                        .IsUnique();

                    b.ToTable("Markets");
                });

            modelBuilder.Entity("MarketService.Domain.Entities.MarketAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte>("ActionType")
                        .HasColumnType("smallint");

                    b.Property<int?>("AnchorErrorNumber")
                        .HasColumnType("integer");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ConfirmedSlot")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("RpcErrorText")
                        .HasColumnType("text");

                    b.Property<byte>("State")
                        .HasColumnType("smallint");

                    b.Property<string>("TxSignature")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("AttemptCount", "CreatedAtUtc");

                    b.HasIndex("ErrorCode", "CreatedAtUtc");

                    b.HasIndex("State", "CreatedAtUtc");

                    b.HasIndex("MarketId", "ActionType", "State");

                    b.ToTable("MarketActions");
                });

            modelBuilder.Entity("MarketService.Domain.Entities.MarketOutcome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid");

                    b.Property<int>("OutcomeIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MarketId", "OutcomeIndex")
                        .IsUnique();

                    b.ToTable("MarketOutcomes");
                });

            modelBuilder.Entity("MarketService.Domain.Entities.MarketResolution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EvidenceUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("ResolveTxSignature")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ResolvedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<int>("WinningOutcomeIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MarketId")
                        .IsUnique();

                    b.ToTable("MarketResolutions");
                });

            modelBuilder.Entity("MarketService.Domain.Entities.UserMarketPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Claimed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("LastSyncedSlot")
                        .HasColumnType("numeric(20,0)");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("NoShares")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("PositionPubKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("YesShares")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("MarketId");

                    b.HasIndex("PositionPubKey")
                        .IsUnique();

                    b.HasIndex("UserId", "MarketId")
                        .IsUnique();

                    b.ToTable("UserMarketPositions");
                });

            modelBuilder.Entity("MarketService.Domain.Entities.MarketAction", b =>
                {
                    b.HasOne("MarketService.Domain.Entities.Market", "Market")
                        .WithMany("Actions")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Market");
                });

            modelBuilder.Entity("MarketService.Domain.Entities.MarketOutcome", b =>
                {
                    b.HasOne("MarketService.Domain.Entities.Market", "Market")
                        .WithMany("Outcomes")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Market");
                });

            modelBuilder.Entity("MarketService.Domain.Entities.MarketResolution", b =>
                {
                    b.HasOne("MarketService.Domain.Entities.Market", "Market")
                        .WithOne("Resolution")
                        .HasForeignKey("MarketService.Domain.Entities.MarketResolution", "MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Market");
                });

            modelBuilder.Entity("MarketService.Domain.Entities.UserMarketPosition", b =>
                {
                    b.HasOne("MarketService.Domain.Entities.Market", "Market")
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Market");
                });

            modelBuilder.Entity("MarketService.Domain.Entities.Market", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Outcomes");

                    b.Navigation("Resolution");
                });
#pragma warning restore 612, 618
        }
    }
}
